### ISSUE TITLE
sum all package downloads next to user name

### ISSUE THREAD

**Issue by capaj** [lukeed/npm-downloads-extension#3]
it would be useful if it could sum all the download counts and add it just after user's user name

**Comment by lukeed** [comment]
Ah, yeah. Would be nice, but I can only (reasonably) total the displayed packages' sum. I feel like that would be confusing or misleading when looking at seasoned authors (like sindresorhus, for example). 

What do you think?

**Comment by capaj** [comment]
oh npm paginates when a user has too many packages? yeah that sucks. Closing then.

**Comment by lukeed** [comment]
Yeah, is quite the bummer. I'll keep an eye out on any API changes to see if this is possible in the future.
